# fly.toml app configuration file generated for brewvine on 2023-04-26T14:01:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brewvine"
primary_region = "lax"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
